# Generated by Django 3.2.2 on 2021-05-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('face_image', models.ImageField(upload_to='images/20210523-182458', verbose_name='人脸照片路径')),
                ('certificate_image', models.ImageField(upload_to='images/20210523-182458', verbose_name='人证照片路径')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='更新时间')),
                ('location', models.CharField(max_length=20, null=True, verbose_name='考场位置')),
                ('similarity', models.CharField(max_length=20, verbose_name='相似度')),
            ],
            options={
                'verbose_name': '所有记录',
                'verbose_name_plural': '所有记录',
            },
        ),
        migrations.CreateModel(
            name='data1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('face_image', models.ImageField(upload_to='images/20210523-182458', verbose_name='人脸照片路径')),
                ('certificate_image', models.ImageField(upload_to='images/20210523-182458', verbose_name='人证照片路径')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='更新时间')),
                ('location', models.CharField(max_length=20, null=True, verbose_name='考场位置')),
                ('similarity', models.CharField(max_length=20, verbose_name='相似度')),
            ],
            options={
                'verbose_name': '未通过记录',
                'verbose_name_plural': '未通过记录',
            },
        ),
    ]
